namespace DevOps.Decorators {
    public class FooterDecorator : ReportDecorator {
        private readonly string _companyName;
        private readonly string _projectName;
        private readonly string _version;
        private readonly DateTime _date;

        public FooterDecorator(IReport report, string companyName, string projectName, string version, DateTime date) : base(report) {
            _companyName = companyName;
            _projectName = projectName;
            _version = version;
            _date = date;
        }

        public override void GenerateReport() {
            base.GenerateReport();
            Console.WriteLine($"Report generated by {_companyName} for {_projectName} (Version {_version}) on {_date}");
        }
    }
}
